// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fleming_single_stage
Rcpp::List fleming_single_stage(double p0, double pa, double alpha, double beta, double eps);
RcppExport SEXP _PhIIdesign_fleming_single_stage(SEXP p0SEXP, SEXP paSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type pa(paSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fleming_single_stage(p0, pa, alpha, beta, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PhIIdesign_fleming_single_stage", (DL_FUNC) &_PhIIdesign_fleming_single_stage, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PhIIdesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
