# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fleming_single_stage <- function(p0, pa, alpha = 0.05, beta = 0.2, eps = 0.005) {
    .Call('_PhIIdesign_fleming_single_stage', PACKAGE = 'PhIIdesign', p0, pa, alpha, beta, eps)
}

