# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_bin_dif_cdf <- function(z, n1, n2, p1, p2, type) {
    .Call('_PhIIdesign_rcpp_bin_dif_cdf', PACKAGE = 'PhIIdesign', z, n1, n2, p1, p2, type)
}

rcpp_exact1stage <- function(p0, pa, alpha, beta, eps = 0.005, alloc = 1L, type = "exact") {
    .Call('_PhIIdesign_rcpp_exact1stage', PACKAGE = 'PhIIdesign', p0, pa, alpha, beta, eps, alloc, type)
}

fleming_single_stage <- function(p0, pa, alpha = 0.05, beta = 0.2, eps = 0.005) {
    .Call('_PhIIdesign_fleming_single_stage', PACKAGE = 'PhIIdesign', p0, pa, alpha, beta, eps)
}

sargent1stage_N_r <- function(N_min, N_max) {
    .Call('_PhIIdesign_sargent1stage_N_r', PACKAGE = 'PhIIdesign', N_min, N_max)
}

sargent1stage_N_r_s <- function(N, r, beta_temp, eta_temp) {
    .Call('_PhIIdesign_sargent1stage_N_r_s', PACKAGE = 'PhIIdesign', N, r, beta_temp, eta_temp)
}

